apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    name: task1
spec:
  containers:
    - name: mahmoud-container
      image: mahmoudgalal2023040383
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"